//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ThanhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhVien()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.KhachHang = new HashSet<KhachHang>();
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MaTV { get; set; }
        [DisplayName("Tài Khoản")]
        [Required(ErrorMessage = "{0} không được để trống")]
        [StringLength(10, ErrorMessage = "Không quá 10 kýtự")]
        public string TaiKhoan { get; set; }
        [DisplayName("Mật Khẩu")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string MatKhau { get; set; }
        [Required(ErrorMessage = "{0} không được để trống")]
        [DisplayName("Họ Tên")]
        public string HoTen { get; set; }
        [DisplayName("Địa Chỉ")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string DiaChi { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "{0} không được để trống")]
        [RegularExpression(@"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", ErrorMessage = "Email khônghợp lệ!")]
        public string Email { get; set; }
        [DisplayName("Số Điên thoại")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string SoDienThoai { get; set; }
        [DisplayName("Câu Hỏi")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string CauHoi { get; set; }
        [DisplayName("Câu Trả Lời")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string CauTraLoi { get; set; }
        public int MaLoaiTV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHang { get; set; }
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
    }
}
